version: '3.9'

networks:
  app-network:

services:
  web-app:
    container_name: '${APP_NAME}-web-app'
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /usr/local/bin/docker-php-entrypoint-dev
    command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
    ports:
      - '${APP_PORT:-8888}:80'
    environment:
      - APP_ENV=local
      - APP_KEY=base64:QQQQyhq8ba8iXBPtpLYdMWGPLrzk+v+f0ARYtHpxk0s=
      - APP_DEBUG=true
      - 'DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@mariadb:3306/${DB_DATABASE}?serverVersion=10.5'
    volumes:
      - ./:/var/www/app
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

  mariadb:
    image: mariadb:10.5
    container_name: '${APP_NAME}-db'
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MARIADB_AUTO_UPGRADE: false
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: '${APP_NAME}-db-admin'
    ports:
      - '${APP_DB_ADMIN_PORT:-8889}:80'
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 256M
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - phpmyadmin-data:/var/www/html
    networks:
      - app-network

volumes:
  db-data:
  phpmyadmin-data:
