version: '3.9'

networks:
  app-network:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      - CI_ENV=development
      - 'DATABASE_URL=mysql://${DB_USERNAME:-codeigniter}:${DB_PASSWORD:-codeigniter}@mariadb:3306/${DB_DATABASE:-codeigniter}?serverVersion=10.5'
    volumes:
      - ./:/var/www/app
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

  mariadb:
    image: mariadb:10.5
    restart: always
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MARIADB_AUTO_UPGRADE: false
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_USER: '${DB_USERNAME:-codeigniter}'
      MYSQL_PASSWORD: '${DB_PASSWORD-codeigniter}'
      MYSQL_DATABASE: '${DB_DATABASE-codeigniter}'
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '${APP_DB_ADMIN_PORT:-8080}:80'
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 256M
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - phpmyadmin-data:/var/www/html
    networks:
      - app-network

volumes:
  db-data:
  phpmyadmin-data:
